# Generated by Django 5.1.5 on 2025-01-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=150)),
                ('talle', models.CharField(max_length=2)),
                ('mail', models.EmailField(max_length=254)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
