# Generated by Django 5.1.5 on 2025-01-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=80)),
                ('asunto', models.CharField(max_length=150)),
                ('contenido', models.TextField(max_length=200)),
                ('nombre_asistente', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Comprar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=150)),
                ('talle', models.CharField(max_length=2)),
                ('mail', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=300)),
                ('banco', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=150)),
                ('talle', models.CharField(max_length=2)),
                ('mail', models.EmailField(max_length=254)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
