# Generated by Django 5.1.5 on 2025-01-27 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ak_Clientes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Comprar',
        ),
        migrations.DeleteModel(
            name='Reservar',
        ),
    ]
